// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtE2ZLmBKXYqJy0Z8Uy2MEMkQ8s4BbiBs',
    appId: '1:531500741475:web:baec30242bfbb33d62d956',
    messagingSenderId: '531500741475',
    projectId: 'flutterloginfirebase-f78fc',
    authDomain: 'flutterloginfirebase-f78fc.firebaseapp.com',
    storageBucket: 'flutterloginfirebase-f78fc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1UdI-rlyKq3XOJIZaiDj5bqbttHX7gCE',
    appId: '1:531500741475:android:5b54f7810b921f4f62d956',
    messagingSenderId: '531500741475',
    projectId: 'flutterloginfirebase-f78fc',
    storageBucket: 'flutterloginfirebase-f78fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD9ZdF7Ng1eao6_okbD_0RfsNgGUaZXDg',
    appId: '1:531500741475:ios:89f25a3efd2fea7e62d956',
    messagingSenderId: '531500741475',
    projectId: 'flutterloginfirebase-f78fc',
    storageBucket: 'flutterloginfirebase-f78fc.firebasestorage.app',
    iosBundleId: 'com.example.flutterloginfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBD9ZdF7Ng1eao6_okbD_0RfsNgGUaZXDg',
    appId: '1:531500741475:ios:89f25a3efd2fea7e62d956',
    messagingSenderId: '531500741475',
    projectId: 'flutterloginfirebase-f78fc',
    storageBucket: 'flutterloginfirebase-f78fc.firebasestorage.app',
    iosBundleId: 'com.example.flutterloginfirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtE2ZLmBKXYqJy0Z8Uy2MEMkQ8s4BbiBs',
    appId: '1:531500741475:web:db49153ec0c0104562d956',
    messagingSenderId: '531500741475',
    projectId: 'flutterloginfirebase-f78fc',
    authDomain: 'flutterloginfirebase-f78fc.firebaseapp.com',
    storageBucket: 'flutterloginfirebase-f78fc.firebasestorage.app',
  );
}
